# Generated by Django 2.2.11 on 2020-05-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0002_filepath_hostname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indexedfile",
            options={"get_latest_by": "first_seen"},
        ),
    ]
