# Generated by Django 2.2.11 on 2020-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0003_auto_20200529_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedfile",
            name="file",
            field=models.FileField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
