# Generated by Django 2.2.11 on 2020-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0004_indexedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexedfile",
            name="file",
            field=models.FileField(max_length=2048, upload_to=""),
        ),
    ]
