# Generated by Django 4.0.1 on 2022-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0005_auto_20200529_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexedfile",
            name="corrupt",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
