# Generated by Django 4.0.7 on 2023-11-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0006_alter_indexedfile_corrupt"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexedImage",
            fields=[
                (
                    "indexedfile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="fileindex.indexedfile",
                    ),
                ),
                (
                    "thumbhash",
                    models.CharField(
                        default=False, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Height",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Width",
                    ),
                ),
            ],
        ),
    ]
