# Generated by Django 4.0.7 on 2023-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileindex", "0007_indexedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexedimage",
            name="thumbhash",
            field=models.CharField(
                default=None, editable=False, max_length=255, null=True
            ),
        ),
    ]
