# Generated by Django 5.0.1 on 2024-06-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileindex", "0008_alter_indexedimage_thumbhash"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedfile",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_files",
                to="fileindex.indexedfile",
            ),
        ),
    ]
